"""A lightweight backbone inspired by the Covariant Particle Transformer
(Qiu, Han, Ju, Nachman & Wang, "A Holistic Approach to Predicting Top Quark
Kinematic Properties with the Covariant Particle Transformer",
arXiv:2203.05687; code: https://github.com/shikaiqiu/Covariant-Particle-Transformer).

At a hadron collider the full Lorentz group SO+(1,3) is more symmetry than
the data actually has: the beam fixes a preferred axis, so the physically
meaningful residual symmetry is the subgroup generated by longitudinal
boosts along the beam and azimuthal rotations about it, SO(2) x SO+(1,1).
Two different lab-frame views of the *same* collision differ by exactly a
transformation from this subgroup (different parton longitudinal momentum
fractions -> different net longitudinal boost of the hard-scatter system;
detector phi is an arbitrary convention -> global rotation about the beam).
An observable like an invariant mass shouldn't -- and mathematically
doesn't -- depend on which of these equivalent views you happened to
measure from, so it's worth building that into the network rather than
hoping enough training data covers every boost.

The trick (shared with the original CPT, LorentzNet, and similar
"beam-symmetric" architectures): work in (pT, y, phi, m) instead of
(px, py, pz, E). pT and m are already invariant under this subgroup;
rapidity y shifts additively under a longitudinal boost (y -> y + beta);
azimuthal angle phi shifts additively under a beam-axis rotation
(phi -> phi + alpha). So split every object's representation into

* an **invariant channel** ``x`` (built from pT, m, and any other already-
  invariant per-object features like a b-tag score) that ordinary MLPs/
  attention can process with no restrictions at all -- any function of
  invariants is itself invariant, and
* a **covariant channel** ``(y, cos(phi), sin(phi))`` (kept as a unit
  vector to sidestep angle wraparound) that may only be updated by adding
  an *invariant* increment (for y) or composing an *invariant* rotation
  (for phi/cos-sin) -- an invariant shift is by definition unaffected by
  the transform, so `y_new = y + delta` picks up exactly the same
  boost the original y did, and likewise for phi. That's what makes the
  update covariant rather than merely "some numbers that happen to change".

Pairwise attention is conditioned on the boost/rotation-*invariant*
relative descriptor of object j as seen from object i,
``omega_ij = (y_j - y_i, cos(phi_j - phi_i), sin(phi_j - phi_i))``
(the phi terms via angle-addition identities on the unit vectors, so no
raw angle subtraction / wraparound handling is needed anywhere). Since
every input to the attention mechanism -- the invariant channel and
omega_ij -- is unchanged by a common boost+rotation applied to every object
in an event, the attention weights and the resulting pooled event embedding
this backbone produces are *exactly* invariant under that transform (see
``tests/test_backbone_covariant.py::test_boost_and_rotation_invariance``,
which checks this numerically to floating-point precision). That pooled,
invariant embedding is what feeds the regression head, which is exactly
the useful property for something like an invariant-mass target.

Simplifications relative to the paper (deliberate -- "lightweight", and I
haven't read the authors' actual code, only the paper): only an *encoder*
is implemented here (their 6-layer covariant self-attention stack), not
their cross-attention decoder for autoregressively reconstructing unseen
particles (e.g. a top quark's own four-vector) -- this package regresses
scalar/vector observables from a pooled event embedding, which doesn't need
that decoder. Only longitudinal boosts + azimuthal rotations are covered
(matching the paper's own scope, "partial" covariance) -- transverse boosts
and time-reversal etc. are not, since they're not the physically relevant
symmetry for LHC final states. Pooling only supports ``"mean"``/
``"attention"`` (no ``"cls"``): a CLS token has no physical four-vector, so
rather than bolt on special-cased zero-omega handling for it (as
``PairformerBackbone`` does), masked pooling directly over the
already-invariant per-object embeddings is simpler and equally principled.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
from torch import Tensor

from hepsetreg.models.pooling import build_pooling


@dataclass
class KinematicGroupSpec:
    """Describes one object type for :class:`CovariantParticleTransformer`.

    Unlike :class:`~hepsetreg.models.tokenizer.ObjectGroupSpec` (used by the
    other backbones for opaque, arbitrary-width feature vectors), this
    backbone needs to know which raw inputs are actually a four-vector, so
    it can compute (pT, m, y, phi) itself -- ``extra_features`` is only for
    *additional*, already boost/rotation-invariant scalars you want to feed
    in alongside pT/m (e.g. a b-tag score, particle ID, isolation). Do not
    put px/py/pz/E-derived quantities in ``extra_features``: doing so would
    reintroduce the frame-dependence this backbone exists to avoid.
    """

    name: str
    extra_features: int = 0


def apply_beam_symmetry_transform(
    four_vectors: Tensor, delta_rapidity: Tensor, delta_phi: Tensor
) -> Tensor:
    """Applies a longitudinal boost (rapidity shift ``delta_rapidity``) and
    an azimuthal rotation about the beam axis (``delta_phi``) to a batch of
    four-vectors ``(..., 4)`` in ``(px, py, pz, E)`` order.

    This is exactly the symmetry transform :class:`CovariantParticleTransformer`
    is built to be invariant to -- useful both for testing that invariance
    (apply it to a batch and confirm the pooled output doesn't move) and as
    a physically-meaningful data-augmentation for any of this package's
    other backbones.

    ``delta_rapidity``/``delta_phi`` broadcast against ``four_vectors``'s
    leading dims, so a shape ``(batch, 1)`` shift (one random boost/rotation
    per *event*, shared across every object in that event -- the physically
    correct usage) broadcasts naturally against ``(batch, n_objects, 4)``.
    """
    px, py, pz, e = four_vectors.unbind(dim=-1)
    pt = torch.sqrt(px**2 + py**2)
    phi = torch.atan2(py, px)
    mass2 = (e**2 - px**2 - py**2 - pz**2).clamp(min=0.0)
    denom_pos = (e + pz).clamp(min=1e-12)
    denom_neg = (e - pz).clamp(min=1e-12)
    rapidity = 0.5 * torch.log(denom_pos / denom_neg)

    delta_rapidity = torch.as_tensor(delta_rapidity, dtype=four_vectors.dtype, device=four_vectors.device)
    delta_phi = torch.as_tensor(delta_phi, dtype=four_vectors.dtype, device=four_vectors.device)

    new_rapidity = rapidity + delta_rapidity
    new_phi = phi + delta_phi
    transverse_mass = torch.sqrt(pt**2 + mass2)

    new_px = pt * torch.cos(new_phi)
    new_py = pt * torch.sin(new_phi)
    new_pz = transverse_mass * torch.sinh(new_rapidity)
    new_e = transverse_mass * torch.cosh(new_rapidity)
    return torch.stack([new_px, new_py, new_pz, new_e], dim=-1)


def _pairwise_omega(y: Tensor, cos_phi: Tensor, sin_phi: Tensor) -> Tensor:
    """omega[b, i, j] = (y_j - y_i, cos(phi_j - phi_i), sin(phi_j - phi_i)),
    the invariant "flight direction of j as seen from i's frame". The phi
    terms come from angle-addition identities on (cos_phi, sin_phi) so no
    raw angle is ever subtracted (no wraparound handling needed)."""
    dy = y.unsqueeze(1) - y.unsqueeze(2)  # [b, i, j] = y_j - y_i
    cos_diff = cos_phi.unsqueeze(1) * cos_phi.unsqueeze(2) + sin_phi.unsqueeze(1) * sin_phi.unsqueeze(2)
    sin_diff = sin_phi.unsqueeze(1) * cos_phi.unsqueeze(2) - cos_phi.unsqueeze(1) * sin_phi.unsqueeze(2)
    return torch.stack([dy, cos_diff, sin_diff], dim=-1)


class CovariantAttention(nn.Module):
    """Self-attention over the invariant channel ``x``, with keys and values
    additionally conditioned on the pairwise invariant descriptor
    ``omega_ij`` -- so both "what object j contains" (content) and "where
    object j is relative to i" (invariant relative geometry) inform the
    attention weights and the aggregated message, while everything that
    enters the computation is itself invariant.
    """

    def __init__(self, d_model: int, nhead: int, dropout: float = 0.0):
        super().__init__()
        if d_model % nhead != 0:
            raise ValueError(f"d_model ({d_model}) must be divisible by nhead ({nhead}).")
        self.nhead = nhead
        self.d_head = d_model // nhead

        self.norm = nn.LayerNorm(d_model)
        self.rel_mlp = nn.Sequential(nn.Linear(3, d_model), nn.GELU(), nn.Linear(d_model, d_model))
        self.q_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_rel_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_rel_proj = nn.Linear(d_model, d_model, bias=False)
        self.out_proj = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: Tensor, omega_pairwise: Tensor, key_padding_mask: Tensor) -> Tensor:
        # x: (B, N, d_model); omega_pairwise: (B, N, N, 3); key_padding_mask: (B, N) bool, True=pad.
        batch_size, n_obj, _ = x.shape
        xn = self.norm(x)
        rel = self.rel_mlp(omega_pairwise)  # (B, N, N, d_model)

        q = self.q_proj(xn).view(batch_size, n_obj, self.nhead, self.d_head)
        k_content = self.k_proj(xn).view(batch_size, n_obj, self.nhead, self.d_head)
        v_content = self.v_proj(xn).view(batch_size, n_obj, self.nhead, self.d_head)
        k_rel = self.k_rel_proj(rel).view(batch_size, n_obj, n_obj, self.nhead, self.d_head)
        v_rel = self.v_rel_proj(rel).view(batch_size, n_obj, n_obj, self.nhead, self.d_head)

        # k_ij / v_ij = content of j, plus a term conditioned on j's invariant position relative to i.
        k = k_content.unsqueeze(1) + k_rel  # (B, N_i, N_j, nhead, d_head)
        v = v_content.unsqueeze(1) + v_rel

        logits = torch.einsum("bihc,bijhc->bhij", q, k) / (self.d_head**0.5)
        key_invalid = key_padding_mask.view(batch_size, 1, 1, n_obj)
        logits = logits.masked_fill(key_invalid, float("-inf"))

        attn = self.dropout(torch.softmax(logits, dim=-1))
        out = torch.einsum("bhij,bijhc->bihc", attn, v)
        out = out.reshape(batch_size, n_obj, self.nhead * self.d_head)
        return self.out_proj(out)


class CovariantTransition(nn.Module):
    """Ordinary pre-LayerNorm MLP applied to the invariant channel -- safe
    because any function of invariants is still invariant."""

    def __init__(self, d_model: int, expansion: float = 4.0, dropout: float = 0.0):
        super().__init__()
        hidden = int(d_model * expansion)
        self.norm = nn.LayerNorm(d_model)
        self.net = nn.Sequential(
            nn.Linear(d_model, hidden), nn.GELU(), nn.Dropout(dropout), nn.Linear(hidden, d_model)
        )

    def forward(self, x: Tensor) -> Tensor:
        return self.net(self.norm(x))


class CovariantBlock(nn.Module):
    """One block: attend + transition on the invariant channel ``x``, then
    use the (updated, still invariant) ``x`` to produce a covariant update
    to ``(y, cos_phi, sin_phi)`` -- an invariant additive shift for
    rapidity, an invariant rotation composed onto the (cos, sin) unit
    vector for phi. Both are covariant by construction: see the module
    docstring."""

    def __init__(self, d_model: int, nhead: int, transition_expansion: float = 4.0, dropout: float = 0.0):
        super().__init__()
        self.attn = CovariantAttention(d_model, nhead, dropout=dropout)
        self.transition = CovariantTransition(d_model, expansion=transition_expansion, dropout=dropout)
        self.y_update = nn.Sequential(
            nn.LayerNorm(d_model), nn.Linear(d_model, d_model), nn.GELU(), nn.Linear(d_model, 1)
        )
        self.phi_update = nn.Sequential(
            nn.LayerNorm(d_model), nn.Linear(d_model, d_model), nn.GELU(), nn.Linear(d_model, 2)
        )

    def forward(
        self,
        x: Tensor,
        cos_phi: Tensor,
        sin_phi: Tensor,
        y: Tensor,
        valid_mask: Tensor,
        key_padding_mask: Tensor,
        eps: float = 1e-6,
    ) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
        omega = _pairwise_omega(y, cos_phi, sin_phi)
        x = x + self.attn(x, omega, key_padding_mask)
        x = x + self.transition(x)
        x = x * valid_mask.unsqueeze(-1).to(x.dtype)

        delta_y = self.y_update(x).squeeze(-1)
        y = y + delta_y * valid_mask.to(y.dtype)

        rot = self.phi_update(x)  # (B, N, 2), an invariant "rotation generator"
        rot_norm = rot.norm(dim=-1).clamp(min=eps)
        cos_delta = rot[..., 0] / rot_norm
        sin_delta = rot[..., 1] / rot_norm
        cos_phi, sin_phi = (
            cos_phi * cos_delta - sin_phi * sin_delta,
            cos_phi * sin_delta + sin_phi * cos_delta,
        )

        return x, cos_phi, sin_phi, y


class CovariantParticleTransformer(nn.Module):
    """Lightweight, boost/rotation-covariant alternative to
    :class:`~hepsetreg.models.backbone.ObjectSetEncoder`, inspired by the
    Covariant Particle Transformer (see module docstring). Same overall
    shape of contract as the other backbones (``forward(..., mask) ->
    pooled``), but takes explicit four-vectors rather than opaque feature
    vectors, since it needs to compute (pT, m, y, phi) itself.

    Parameters
    ----------
    groups:
        List of :class:`KinematicGroupSpec`, one per object type.
    d_model, nhead, num_blocks:
        Standard transformer-ish sizing. AF3/CPT-scale stacks use many more
        blocks than the default here; "lightweight" -> a handful is a
        reasonable starting point for jet/lepton-scale object counts.
    pooling:
        ``"mean"`` or ``"attention"`` only -- see module docstring for why
        ``"cls"`` isn't offered here.
    log_pt_and_mass:
        Apply ``log1p`` to pT and mass before the invariant-channel
        projection (both are strictly positive and span a huge dynamic
        range; this is purely a conditioning choice and doesn't affect
        covariance either way, since log of an invariant is still
        invariant).
    """

    def __init__(
        self,
        groups: List[KinematicGroupSpec],
        d_model: int = 64,
        nhead: int = 4,
        num_blocks: int = 4,
        pooling: str = "mean",
        use_type_embedding: bool = True,
        dropout: float = 0.0,
        transition_expansion: float = 4.0,
        log_pt_and_mass: bool = True,
        eps: float = 1e-6,
    ):
        super().__init__()
        if d_model % nhead != 0:
            raise ValueError(f"d_model ({d_model}) must be divisible by nhead ({nhead}).")
        pooling = pooling.lower()
        if pooling not in {"mean", "attention"}:
            raise ValueError(
                "CovariantParticleTransformer supports pooling='mean' or 'attention' only "
                "(no 'cls' -- a CLS token has no physical four-vector; see the module docstring)."
            )

        self.groups = list(groups)
        self.eps = eps
        self.log_pt_and_mass = log_pt_and_mass

        self.invariant_proj = nn.ModuleDict(
            {g.name: nn.Linear(2 + g.extra_features, d_model) for g in self.groups}
        )
        self.type_embedding = nn.Embedding(len(self.groups), d_model) if use_type_embedding else None

        self.blocks = nn.ModuleList(
            [
                CovariantBlock(d_model, nhead, transition_expansion=transition_expansion, dropout=dropout)
                for _ in range(num_blocks)
            ]
        )
        self.output_norm = nn.LayerNorm(d_model)
        self.pool = build_pooling(pooling, d_model)
        self.d_model = d_model

    def _kinematics(self, four_vector: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor]:
        px, py, pz, e = four_vector.unbind(dim=-1)
        pt = torch.sqrt(px**2 + py**2)
        pt_safe = pt.clamp(min=self.eps)
        cos_phi = px / pt_safe
        sin_phi = py / pt_safe
        mass2 = e**2 - px**2 - py**2 - pz**2
        mass = torch.sqrt(mass2.clamp(min=self.eps**2))
        denom_pos = (e + pz).clamp(min=self.eps)
        denom_neg = (e - pz).clamp(min=self.eps)
        rapidity = 0.5 * torch.log(denom_pos / denom_neg)
        return pt, mass, cos_phi, sin_phi, rapidity

    def forward(
        self,
        four_vectors: Dict[str, Tensor],
        mask: Dict[str, Tensor],
        extra_features: Optional[Dict[str, Tensor]] = None,
        return_tokens: bool = False,
    ):
        extra_features = extra_features or {}
        x_chunks, mask_chunks, cos_chunks, sin_chunks, y_chunks = [], [], [], [], []

        for type_id, group in enumerate(self.groups):
            name = group.name
            if name not in four_vectors or name not in mask:
                raise KeyError(
                    f"CovariantParticleTransformer expected object group '{name}' in "
                    f"`four_vectors`/`mask`; got four_vectors={list(four_vectors)} mask={list(mask)}."
                )
            fv = four_vectors[name]
            if fv.shape[-1] != 4:
                raise ValueError(
                    f"four_vectors['{name}'] must have a last dim of 4 (px, py, pz, E); got {tuple(fv.shape)}."
                )
            valid = mask[name].bool()

            pt, mass, cos_phi, sin_phi, y = self._kinematics(fv)
            pt_feat = torch.log1p(pt) if self.log_pt_and_mass else pt
            mass_feat = torch.log1p(mass) if self.log_pt_and_mass else mass
            scalar_parts = [pt_feat.unsqueeze(-1), mass_feat.unsqueeze(-1)]

            extra = extra_features.get(name)
            if group.extra_features > 0:
                if extra is None:
                    raise ValueError(
                        f"Object group '{name}' was configured with extra_features="
                        f"{group.extra_features} but no extra_features['{name}'] tensor was "
                        f"passed to forward()."
                    )
                if extra.shape[-1] != group.extra_features:
                    raise ValueError(
                        f"extra_features['{name}'] last dim {extra.shape[-1]} != configured "
                        f"{group.extra_features}."
                    )
                scalar_parts.append(extra)
            elif extra is not None:
                raise ValueError(f"extra_features['{name}'] was passed but group '{name}' has extra_features=0.")

            scalars = torch.cat(scalar_parts, dim=-1)
            x = self.invariant_proj[name](scalars)
            if self.type_embedding is not None:
                type_ids = torch.full(valid.shape, type_id, dtype=torch.long, device=fv.device)
                x = x + self.type_embedding(type_ids)
            x = x * valid.unsqueeze(-1).to(x.dtype)

            x_chunks.append(x)
            mask_chunks.append(valid)
            cos_chunks.append(cos_phi)
            sin_chunks.append(sin_phi)
            y_chunks.append(y)

        x = torch.cat(x_chunks, dim=1)
        valid_mask = torch.cat(mask_chunks, dim=1)
        cos_phi = torch.cat(cos_chunks, dim=1)
        sin_phi = torch.cat(sin_chunks, dim=1)
        y = torch.cat(y_chunks, dim=1)

        if not valid_mask.any(dim=1).all():
            raise ValueError(
                "Found an event with no valid objects at all (mask is all-False); "
                "CovariantParticleTransformer needs >=1 real object per event."
            )

        key_padding_mask = ~valid_mask
        for block in self.blocks:
            x, cos_phi, sin_phi, y = block(x, cos_phi, sin_phi, y, valid_mask, key_padding_mask, eps=self.eps)

        x = self.output_norm(x)
        pooled = self.pool(x, valid_mask)

        if return_tokens:
            return pooled, x, valid_mask, {"cos_phi": cos_phi, "sin_phi": sin_phi, "rapidity": y}
        return pooled
